version: "3.9"

services:
  qbizy-maintenance-db:
    image: postgres:17
    container_name: postgres17
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
    ports:
      - "7055:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
