import { ROUTES } from '@const/routes'

export const PUBLIC_ROUTES = [
    ROUTES.PUBLIC_HOME,
    ROUTES.PUBLIC_FAVICON,
    ROUTES.PUBLIC_DOCS,
    ROUTES.PUBLIC_DOC,
    ROUTES.PUBLIC_DEV_DOC,
    ROUTES.PUBLIC_MAINTENANCE,
]
